/*
 * regexutils.c
 */

#include "regexutils.h"
#include <math.h>

#define SETRCERROR(str)  strcpy(rcerror, str); break

void translate_error(int use_old_ver, int rc, char * rcerror) {
#ifdef WITH_OLD_PCRE
    if (use_old_ver == 1) {
        switch (rc) {
            case  PCRE_ERROR_NOMATCH:           SETRCERROR("NOT MATCHED");
            case  PCRE_ERROR_NULL:              SETRCERROR("NULL ERROR");
            case  PCRE_ERROR_BADOPTION:         SETRCERROR("BAD OPTION");
            case  PCRE_ERROR_BADMAGIC:          SETRCERROR("BAD MAGIC");
            case  PCRE_ERROR_UNKNOWN_OPCODE:    SETRCERROR("UNKNOWN OPCODE");
            case  PCRE_ERROR_NOMEMORY:          SETRCERROR("NO MEMORY");
            case  PCRE_ERROR_NOSUBSTRING:       SETRCERROR("NO SUBSTRING");
            case  PCRE_ERROR_MATCHLIMIT:        SETRCERROR("MATCH LIMIT");
            case  PCRE_ERROR_CALLOUT:           SETRCERROR("CALL OUT");
            case  PCRE_ERROR_BADUTF8:           SETRCERROR("BAD UTF");
            case  PCRE_ERROR_BADUTF8_OFFSET:    SETRCERROR("BAD UTF OFFSET");
            case  PCRE_ERROR_PARTIAL:           SETRCERROR("PARTIAL ERROR");
            case  PCRE_ERROR_BADPARTIAL:        SETRCERROR("BAD PARTIAL ERROR");
            case  PCRE_ERROR_INTERNAL:          SETRCERROR("INTERNAL ERROR");
            case  PCRE_ERROR_BADCOUNT:          SETRCERROR("BAD COUNT");
            case  PCRE_ERROR_DFA_UITEM:         SETRCERROR("DFA UITEM");
            case  PCRE_ERROR_DFA_UCOND:         SETRCERROR("DFA UCOND");
            case  PCRE_ERROR_DFA_UMLIMIT:       SETRCERROR("DFA UMLIMIT");
            case  PCRE_ERROR_DFA_WSSIZE:        SETRCERROR("DFA WSSIZE");
            case  PCRE_ERROR_DFA_RECURSE:       SETRCERROR("DFA RECURSE");
            case  PCRE_ERROR_RECURSIONLIMIT:    SETRCERROR("RECURSION LIMIT");
            case  PCRE_ERROR_NULLWSLIMIT:       SETRCERROR("NULL WS LIMIT");
            case  PCRE_ERROR_BADNEWLINE:        SETRCERROR("BAD NEWLINE");
            case  PCRE_ERROR_BADOFFSET:         SETRCERROR("BAD OFFSET");
            case  PCRE_ERROR_SHORTUTF8:         SETRCERROR("SHORT UTF");
            case  PCRE_ERROR_RECURSELOOP:       SETRCERROR("RECURSE LOOP");
            case  PCRE_ERROR_JIT_STACKLIMIT:    SETRCERROR("JIT STACKLIMIT");
            case  PCRE_ERROR_BADMODE:           SETRCERROR("BAD MODE");
            case  PCRE_ERROR_BADENDIANNESS:     SETRCERROR("BAD ENDIANNESS");
            case  PCRE_ERROR_DFA_BADRESTART:    SETRCERROR("DFA BAD RESTART");
            case  PCRE_ERROR_JIT_BADOPTION:     SETRCERROR("JIT BAD OPTION");
            case  PCRE_ERROR_BADLENGTH:         SETRCERROR("BAD LENGTH");
            case  PCRE_ERROR_UNSET:             SETRCERROR("UNSET");
            default:
                if (rc < 0) {
                    SETRCERROR("UNKNOWN ERROR");
                }
                else if (rc == 0) {
                    SETRCERROR("OVECTOR OUT OF SPACE");
                }
                else {
                    sprintf(rcerror, "SUBJECT MATCHED %d TIME%s", rc, ((rc > 1) ? "S" : ""));
                }
        }
    }
    else {
#endif
        switch(rc) {
            case PCRE2_ERROR_END_BACKSLASH:                    SETRCERROR("PCRE2 ERROR END BACKSLASH");
            case PCRE2_ERROR_END_BACKSLASH_C:                  SETRCERROR("PCRE2 ERROR END BACKSLASH C");
            case PCRE2_ERROR_UNKNOWN_ESCAPE:                   SETRCERROR("PCRE2 ERROR UNKNOWN ESCAPE");
            case PCRE2_ERROR_QUANTIFIER_OUT_OF_ORDER:          SETRCERROR("PCRE2 ERROR QUANTIFIER OUT OF ORDER");
            case PCRE2_ERROR_QUANTIFIER_TOO_BIG:               SETRCERROR("PCRE2 ERROR QUANTIFIER TOO BIG");
            case PCRE2_ERROR_MISSING_SQUARE_BRACKET:           SETRCERROR("PCRE2 ERROR MISSING SQUARE BRACKET");
            case PCRE2_ERROR_ESCAPE_INVALID_IN_CLASS:          SETRCERROR("PCRE2 ERROR ESCAPE INVALID IN CLASS");
            case PCRE2_ERROR_CLASS_RANGE_ORDER:                SETRCERROR("PCRE2 ERROR CLASS RANGE ORDER");
            case PCRE2_ERROR_QUANTIFIER_INVALID:               SETRCERROR("PCRE2 ERROR QUANTIFIER INVALID");
            case PCRE2_ERROR_INTERNAL_UNEXPECTED_REPEAT:       SETRCERROR("PCRE2 ERROR INTERNAL UNEXPECTED REPEAT");
            case PCRE2_ERROR_INVALID_AFTER_PARENS_QUERY:       SETRCERROR("PCRE2 ERROR INVALID AFTER PARENS QUERY");
            case PCRE2_ERROR_POSIX_CLASS_NOT_IN_CLASS:         SETRCERROR("PCRE2 ERROR POSIX CLASS NOT IN CLASS");
            case PCRE2_ERROR_POSIX_NO_SUPPORT_COLLATING:       SETRCERROR("PCRE2 ERROR POSIX NO SUPPORT COLLATING");
            case PCRE2_ERROR_MISSING_CLOSING_PARENTHESIS:      SETRCERROR("PCRE2 ERROR MISSING CLOSING PARENTHESIS");
            case PCRE2_ERROR_BAD_SUBPATTERN_REFERENCE:         SETRCERROR("PCRE2 ERROR BAD SUBPATTERN REFERENCE");
            case PCRE2_ERROR_NULL_PATTERN:                     SETRCERROR("PCRE2 ERROR NULL PATTERN");
            case PCRE2_ERROR_BAD_OPTIONS:                      SETRCERROR("PCRE2 ERROR BAD OPTIONS");
            case PCRE2_ERROR_MISSING_COMMENT_CLOSING:          SETRCERROR("PCRE2 ERROR MISSING COMMENT CLOSING");
            case PCRE2_ERROR_PARENTHESES_NEST_TOO_DEEP:        SETRCERROR("PCRE2 ERROR PARENTHESES NEST TOO DEEP");
            case PCRE2_ERROR_PATTERN_TOO_LARGE:                SETRCERROR("PCRE2 ERROR PATTERN TOO LARGE");
            case PCRE2_ERROR_HEAP_FAILED:                      SETRCERROR("PCRE2 ERROR HEAP FAILED");
            case PCRE2_ERROR_UNMATCHED_CLOSING_PARENTHESIS:    SETRCERROR("PCRE2 ERROR UNMATCHED CLOSING PARENTHESIS");
            case PCRE2_ERROR_INTERNAL_CODE_OVERFLOW:           SETRCERROR("PCRE2 ERROR INTERNAL CODE OVERFLOW");
            case PCRE2_ERROR_MISSING_CONDITION_CLOSING:        SETRCERROR("PCRE2 ERROR MISSING CONDITION CLOSING");
            case PCRE2_ERROR_LOOKBEHIND_NOT_FIXED_LENGTH:      SETRCERROR("PCRE2 ERROR LOOKBEHIND NOT FIXED LENGTH");
            case PCRE2_ERROR_ZERO_RELATIVE_REFERENCE:          SETRCERROR("PCRE2 ERROR ZERO RELATIVE REFERENCE");
            case PCRE2_ERROR_TOO_MANY_CONDITION_BRANCHES:      SETRCERROR("PCRE2 ERROR TOO MANY CONDITION BRANCHES");
            case PCRE2_ERROR_CONDITION_ASSERTION_EXPECTED:     SETRCERROR("PCRE2 ERROR CONDITION ASSERTION EXPECTED");
            case PCRE2_ERROR_BAD_RELATIVE_REFERENCE:           SETRCERROR("PCRE2 ERROR BAD RELATIVE REFERENCE");
            case PCRE2_ERROR_UNKNOWN_POSIX_CLASS:              SETRCERROR("PCRE2 ERROR UNKNOWN POSIX CLASS");
            case PCRE2_ERROR_INTERNAL_STUDY_ERROR:             SETRCERROR("PCRE2 ERROR INTERNAL STUDY ERROR");
            case PCRE2_ERROR_UNICODE_NOT_SUPPORTED:            SETRCERROR("PCRE2 ERROR UNICODE NOT SUPPORTED");
            case PCRE2_ERROR_PARENTHESES_STACK_CHECK:          SETRCERROR("PCRE2 ERROR PARENTHESES STACK CHECK");
            case PCRE2_ERROR_CODE_POINT_TOO_BIG:               SETRCERROR("PCRE2 ERROR CODE POINT TOO BIG");
            case PCRE2_ERROR_LOOKBEHIND_TOO_COMPLICATED:       SETRCERROR("PCRE2 ERROR LOOKBEHIND TOO COMPLICATED");
            case PCRE2_ERROR_LOOKBEHIND_INVALID_BACKSLASH_C:   SETRCERROR("PCRE2 ERROR LOOKBEHIND INVALID BACKSLASH C");
            case PCRE2_ERROR_UNSUPPORTED_ESCAPE_SEQUENCE:      SETRCERROR("PCRE2 ERROR UNSUPPORTED ESCAPE SEQUENCE");
            case PCRE2_ERROR_CALLOUT_NUMBER_TOO_BIG:           SETRCERROR("PCRE2 ERROR CALLOUT NUMBER TOO BIG");
            case PCRE2_ERROR_MISSING_CALLOUT_CLOSING:          SETRCERROR("PCRE2 ERROR MISSING CALLOUT CLOSING");
            case PCRE2_ERROR_ESCAPE_INVALID_IN_VERB:           SETRCERROR("PCRE2 ERROR ESCAPE INVALID IN VERB");
            case PCRE2_ERROR_UNRECOGNIZED_AFTER_QUERY_P:       SETRCERROR("PCRE2 ERROR UNRECOGNIZED AFTER QUERY P");
            case PCRE2_ERROR_MISSING_NAME_TERMINATOR:          SETRCERROR("PCRE2 ERROR MISSING NAME TERMINATOR");
            case PCRE2_ERROR_DUPLICATE_SUBPATTERN_NAME:        SETRCERROR("PCRE2 ERROR DUPLICATE SUBPATTERN NAME");
            case PCRE2_ERROR_INVALID_SUBPATTERN_NAME:          SETRCERROR("PCRE2 ERROR INVALID SUBPATTERN NAME");
            case PCRE2_ERROR_UNICODE_PROPERTIES_UNAVAILABLE:   SETRCERROR("PCRE2 ERROR UNICODE PROPERTIES UNAVAILABLE");
            case PCRE2_ERROR_MALFORMED_UNICODE_PROPERTY:       SETRCERROR("PCRE2 ERROR MALFORMED UNICODE PROPERTY");
            case PCRE2_ERROR_UNKNOWN_UNICODE_PROPERTY:         SETRCERROR("PCRE2 ERROR UNKNOWN UNICODE PROPERTY");
            case PCRE2_ERROR_SUBPATTERN_NAME_TOO_LONG:         SETRCERROR("PCRE2 ERROR SUBPATTERN NAME TOO LONG");
            case PCRE2_ERROR_TOO_MANY_NAMED_SUBPATTERNS:       SETRCERROR("PCRE2 ERROR TOO MANY NAMED SUBPATTERNS");
            case PCRE2_ERROR_CLASS_INVALID_RANGE:              SETRCERROR("PCRE2 ERROR CLASS INVALID RANGE");
            case PCRE2_ERROR_OCTAL_BYTE_TOO_BIG:               SETRCERROR("PCRE2 ERROR OCTAL BYTE TOO BIG");
            case PCRE2_ERROR_INTERNAL_OVERRAN_WORKSPACE:       SETRCERROR("PCRE2 ERROR INTERNAL OVERRAN WORKSPACE");
            case PCRE2_ERROR_INTERNAL_MISSING_SUBPATTERN:      SETRCERROR("PCRE2 ERROR INTERNAL MISSING SUBPATTERN");
            case PCRE2_ERROR_DEFINE_TOO_MANY_BRANCHES:         SETRCERROR("PCRE2 ERROR DEFINE TOO MANY BRANCHES");
            case PCRE2_ERROR_BACKSLASH_O_MISSING_BRACE:        SETRCERROR("PCRE2 ERROR BACKSLASH O MISSING BRACE");
            case PCRE2_ERROR_INTERNAL_UNKNOWN_NEWLINE:         SETRCERROR("PCRE2 ERROR INTERNAL UNKNOWN NEWLINE");
            case PCRE2_ERROR_BACKSLASH_G_SYNTAX:               SETRCERROR("PCRE2 ERROR BACKSLASH G SYNTAX");
            case PCRE2_ERROR_PARENS_QUERY_R_MISSING_CLOSING:   SETRCERROR("PCRE2 ERROR PARENS QUERY R MISSING CLOSING");
            case PCRE2_ERROR_VERB_ARGUMENT_NOT_ALLOWED:        SETRCERROR("PCRE2 ERROR VERB ARGUMENT NOT ALLOWED");
            case PCRE2_ERROR_VERB_UNKNOWN:                     SETRCERROR("PCRE2 ERROR VERB UNKNOWN");
            case PCRE2_ERROR_SUBPATTERN_NUMBER_TOO_BIG:        SETRCERROR("PCRE2 ERROR SUBPATTERN NUMBER TOO BIG");
            case PCRE2_ERROR_SUBPATTERN_NAME_EXPECTED:         SETRCERROR("PCRE2 ERROR SUBPATTERN NAME EXPECTED");
            case PCRE2_ERROR_INTERNAL_PARSED_OVERFLOW:         SETRCERROR("PCRE2 ERROR INTERNAL PARSED OVERFLOW");
            case PCRE2_ERROR_INVALID_OCTAL:                    SETRCERROR("PCRE2 ERROR INVALID OCTAL");
            case PCRE2_ERROR_SUBPATTERN_NAMES_MISMATCH:        SETRCERROR("PCRE2 ERROR SUBPATTERN NAMES MISMATCH");
            case PCRE2_ERROR_MARK_MISSING_ARGUMENT:            SETRCERROR("PCRE2 ERROR MARK MISSING ARGUMENT");
            case PCRE2_ERROR_INVALID_HEXADECIMAL:              SETRCERROR("PCRE2 ERROR INVALID HEXADECIMAL");
            case PCRE2_ERROR_BACKSLASH_C_SYNTAX:               SETRCERROR("PCRE2 ERROR BACKSLASH C SYNTAX");
            case PCRE2_ERROR_BACKSLASH_K_SYNTAX:               SETRCERROR("PCRE2 ERROR BACKSLASH K SYNTAX");
            case PCRE2_ERROR_INTERNAL_BAD_CODE_LOOKBEHINDS:    SETRCERROR("PCRE2 ERROR INTERNAL BAD CODE LOOKBEHINDS");
            case PCRE2_ERROR_BACKSLASH_N_IN_CLASS:             SETRCERROR("PCRE2 ERROR BACKSLASH N IN CLASS");
            case PCRE2_ERROR_CALLOUT_STRING_TOO_LONG:          SETRCERROR("PCRE2 ERROR CALLOUT STRING TOO LONG");
            case PCRE2_ERROR_UNICODE_DISALLOWED_CODE_POINT:    SETRCERROR("PCRE2 ERROR UNICODE DISALLOWED CODE POINT");
            case PCRE2_ERROR_UTF_IS_DISABLED:                  SETRCERROR("PCRE2 ERROR UTF IS DISABLED");
            case PCRE2_ERROR_UCP_IS_DISABLED:                  SETRCERROR("PCRE2 ERROR UCP IS DISABLED");
            case PCRE2_ERROR_VERB_NAME_TOO_LONG:               SETRCERROR("PCRE2 ERROR VERB NAME TOO LONG");
            case PCRE2_ERROR_BACKSLASH_U_CODE_POINT_TOO_BIG:   SETRCERROR("PCRE2 ERROR BACKSLASH U CODE POINT TOO BIG");
            case PCRE2_ERROR_MISSING_OCTAL_OR_HEX_DIGITS:      SETRCERROR("PCRE2 ERROR MISSING OCTAL OR HEX DIGITS");
            case PCRE2_ERROR_VERSION_CONDITION_SYNTAX:         SETRCERROR("PCRE2 ERROR VERSION CONDITION SYNTAX");
            case PCRE2_ERROR_INTERNAL_BAD_CODE_AUTO_POSSESS:   SETRCERROR("PCRE2 ERROR INTERNAL BAD CODE AUTO POSSESS");
            case PCRE2_ERROR_CALLOUT_NO_STRING_DELIMITER:      SETRCERROR("PCRE2 ERROR CALLOUT NO STRING DELIMITER");
            case PCRE2_ERROR_CALLOUT_BAD_STRING_DELIMITER:     SETRCERROR("PCRE2 ERROR CALLOUT BAD STRING DELIMITER");
            case PCRE2_ERROR_BACKSLASH_C_CALLER_DISABLED:      SETRCERROR("PCRE2 ERROR BACKSLASH C CALLER DISABLED");
            case PCRE2_ERROR_QUERY_BARJX_NEST_TOO_DEEP:        SETRCERROR("PCRE2 ERROR QUERY BARJX NEST TOO DEEP");
            case PCRE2_ERROR_BACKSLASH_C_LIBRARY_DISABLED:     SETRCERROR("PCRE2 ERROR BACKSLASH C LIBRARY DISABLED");
            case PCRE2_ERROR_PATTERN_TOO_COMPLICATED:          SETRCERROR("PCRE2 ERROR PATTERN TOO COMPLICATED");
            case PCRE2_ERROR_LOOKBEHIND_TOO_LONG:              SETRCERROR("PCRE2 ERROR LOOKBEHIND TOO LONG");
            case PCRE2_ERROR_PATTERN_STRING_TOO_LONG:          SETRCERROR("PCRE2 ERROR PATTERN STRING TOO LONG");
            case PCRE2_ERROR_INTERNAL_BAD_CODE:                SETRCERROR("PCRE2 ERROR INTERNAL BAD CODE");
            case PCRE2_ERROR_INTERNAL_BAD_CODE_IN_SKIP:        SETRCERROR("PCRE2 ERROR INTERNAL BAD CODE IN SKIP");
            case PCRE2_ERROR_NO_SURROGATES_IN_UTF16:           SETRCERROR("PCRE2 ERROR NO SURROGATES IN UTF16");
            case PCRE2_ERROR_BAD_LITERAL_OPTIONS:              SETRCERROR("PCRE2 ERROR BAD LITERAL OPTIONS");
            case PCRE2_ERROR_SUPPORTED_ONLY_IN_UNICODE:        SETRCERROR("PCRE2 ERROR SUPPORTED ONLY IN UNICODE");
            case PCRE2_ERROR_INVALID_HYPHEN_IN_OPTIONS:        SETRCERROR("PCRE2 ERROR INVALID HYPHEN IN OPTIONS");
            case PCRE2_ERROR_ALPHA_ASSERTION_UNKNOWN:          SETRCERROR("PCRE2 ERROR ALPHA ASSERTION UNKNOWN");
            case PCRE2_ERROR_SCRIPT_RUN_NOT_AVAILABLE:         SETRCERROR("PCRE2 ERROR SCRIPT RUN NOT AVAILABLE");
            case PCRE2_ERROR_TOO_MANY_CAPTURES:                SETRCERROR("PCRE2 ERROR TOO MANY CAPTURES");
            case PCRE2_ERROR_MISSING_OCTAL_DIGIT:              SETRCERROR("PCRE2 ERROR MISSING OCTAL DIGIT");
            case PCRE2_ERROR_BACKSLASH_K_IN_LOOKAROUND:        SETRCERROR("PCRE2 ERROR BACKSLASH K IN LOOKAROUND");
            case PCRE2_ERROR_MAX_VAR_LOOKBEHIND_EXCEEDED:      SETRCERROR("PCRE2 ERROR MAX VAR LOOKBEHIND EXCEEDED");
            case PCRE2_ERROR_PATTERN_COMPILED_SIZE_TOO_BIG:    SETRCERROR("PCRE2 ERROR PATTERN COMPILED SIZE TOO BIG");
            case PCRE2_ERROR_OVERSIZE_PYTHON_OCTAL:            SETRCERROR("PCRE2 ERROR OVERSIZE PYTHON OCTAL");
            case PCRE2_ERROR_CALLOUT_CALLER_DISABLED:          SETRCERROR("PCRE2 ERROR CALLOUT CALLER DISABLED");
            case PCRE2_ERROR_EXTRA_CASING_REQUIRES_UNICODE:    SETRCERROR("PCRE2 ERROR EXTRA CASING REQUIRES UNICODE");
            case PCRE2_ERROR_TURKISH_CASING_REQUIRES_UTF:      SETRCERROR("PCRE2 ERROR TURKISH CASING REQUIRES UTF");
            case PCRE2_ERROR_EXTRA_CASING_INCOMPATIBLE:        SETRCERROR("PCRE2 ERROR EXTRA CASING INCOMPATIBLE");
            case PCRE2_ERROR_ECLASS_NEST_TOO_DEEP:             SETRCERROR("PCRE2 ERROR ECLASS NEST TOO DEEP");
            case PCRE2_ERROR_ECLASS_INVALID_OPERATOR:          SETRCERROR("PCRE2 ERROR ECLASS INVALID OPERATOR");
            case PCRE2_ERROR_ECLASS_UNEXPECTED_OPERATOR:       SETRCERROR("PCRE2 ERROR ECLASS UNEXPECTED OPERATOR");
            case PCRE2_ERROR_ECLASS_EXPECTED_OPERAND:          SETRCERROR("PCRE2 ERROR ECLASS EXPECTED OPERAND");
            case PCRE2_ERROR_ECLASS_MIXED_OPERATORS:           SETRCERROR("PCRE2 ERROR ECLASS MIXED OPERATORS");
            case PCRE2_ERROR_ECLASS_HINT_SQUARE_BRACKET:       SETRCERROR("PCRE2 ERROR ECLASS HINT SQUARE BRACKET");
            case PCRE2_ERROR_PERL_ECLASS_UNEXPECTED_EXPR:      SETRCERROR("PCRE2 ERROR PERL ECLASS UNEXPECTED EXPR");
            case PCRE2_ERROR_PERL_ECLASS_EMPTY_EXPR:           SETRCERROR("PCRE2 ERROR PERL ECLASS EMPTY EXPR");
            case PCRE2_ERROR_PERL_ECLASS_MISSING_CLOSE:        SETRCERROR("PCRE2 ERROR PERL ECLASS MISSING CLOSE");
            case PCRE2_ERROR_PERL_ECLASS_UNEXPECTED_CHAR:      SETRCERROR("PCRE2 ERROR PERL ECLASS UNEXPECTED CHAR");
            case PCRE2_ERROR_NOMATCH:                          SETRCERROR("PCRE2 ERROR NOMATCH");
            case PCRE2_ERROR_PARTIAL:                          SETRCERROR("PCRE2 ERROR PARTIAL");
            case PCRE2_ERROR_UTF8_ERR1:                        SETRCERROR("PCRE2 ERROR UTF8 ERR1");
            case PCRE2_ERROR_UTF8_ERR2:                        SETRCERROR("PCRE2 ERROR UTF8 ERR2");
            case PCRE2_ERROR_UTF8_ERR3:                        SETRCERROR("PCRE2 ERROR UTF8 ERR3");
            case PCRE2_ERROR_UTF8_ERR4:                        SETRCERROR("PCRE2 ERROR UTF8 ERR4");
            case PCRE2_ERROR_UTF8_ERR5:                        SETRCERROR("PCRE2 ERROR UTF8 ERR5");
            case PCRE2_ERROR_UTF8_ERR6:                        SETRCERROR("PCRE2 ERROR UTF8 ERR6");
            case PCRE2_ERROR_UTF8_ERR7:                        SETRCERROR("PCRE2 ERROR UTF8 ERR7");
            case PCRE2_ERROR_UTF8_ERR8:                        SETRCERROR("PCRE2 ERROR UTF8 ERR8");
            case PCRE2_ERROR_UTF8_ERR9:                        SETRCERROR("PCRE2 ERROR UTF8 ERR9");
            case PCRE2_ERROR_UTF8_ERR10:                       SETRCERROR("PCRE2 ERROR UTF8 ERR10");
            case PCRE2_ERROR_UTF8_ERR11:                       SETRCERROR("PCRE2 ERROR UTF8 ERR11");
            case PCRE2_ERROR_UTF8_ERR12:                       SETRCERROR("PCRE2 ERROR UTF8 ERR12");
            case PCRE2_ERROR_UTF8_ERR13:                       SETRCERROR("PCRE2 ERROR UTF8 ERR13");
            case PCRE2_ERROR_UTF8_ERR14:                       SETRCERROR("PCRE2 ERROR UTF8 ERR14");
            case PCRE2_ERROR_UTF8_ERR15:                       SETRCERROR("PCRE2 ERROR UTF8 ERR15");
            case PCRE2_ERROR_UTF8_ERR16:                       SETRCERROR("PCRE2 ERROR UTF8 ERR16");
            case PCRE2_ERROR_UTF8_ERR17:                       SETRCERROR("PCRE2 ERROR UTF8 ERR17");
            case PCRE2_ERROR_UTF8_ERR18:                       SETRCERROR("PCRE2 ERROR UTF8 ERR18");
            case PCRE2_ERROR_UTF8_ERR19:                       SETRCERROR("PCRE2 ERROR UTF8 ERR19");
            case PCRE2_ERROR_UTF8_ERR20:                       SETRCERROR("PCRE2 ERROR UTF8 ERR20");
            case PCRE2_ERROR_UTF8_ERR21:                       SETRCERROR("PCRE2 ERROR UTF8 ERR21");
            case PCRE2_ERROR_UTF16_ERR1:                       SETRCERROR("PCRE2 ERROR UTF16 ERR1");
            case PCRE2_ERROR_UTF16_ERR2:                       SETRCERROR("PCRE2 ERROR UTF16 ERR2");
            case PCRE2_ERROR_UTF16_ERR3:                       SETRCERROR("PCRE2 ERROR UTF16 ERR3");
            case PCRE2_ERROR_UTF32_ERR1:                       SETRCERROR("PCRE2 ERROR UTF32 ERR1");
            case PCRE2_ERROR_UTF32_ERR2:                       SETRCERROR("PCRE2 ERROR UTF32 ERR2");
            case PCRE2_ERROR_BADDATA:                          SETRCERROR("PCRE2 ERROR BADDATA");
            case PCRE2_ERROR_MIXEDTABLES:                      SETRCERROR("PCRE2 ERROR MIXEDTABLES");
            case PCRE2_ERROR_BADMAGIC:                         SETRCERROR("PCRE2 ERROR BADMAGIC");
            case PCRE2_ERROR_BADMODE:                          SETRCERROR("PCRE2 ERROR BADMODE");
            case PCRE2_ERROR_BADOFFSET:                        SETRCERROR("PCRE2 ERROR BADOFFSET");
            case PCRE2_ERROR_BADOPTION:                        SETRCERROR("PCRE2 ERROR BADOPTION");
            case PCRE2_ERROR_BADREPLACEMENT:                   SETRCERROR("PCRE2 ERROR BADREPLACEMENT");
            case PCRE2_ERROR_BADUTFOFFSET:                     SETRCERROR("PCRE2 ERROR BADUTFOFFSET");
            case PCRE2_ERROR_CALLOUT:                          SETRCERROR("PCRE2 ERROR CALLOUT");
            case PCRE2_ERROR_DFA_BADRESTART:                   SETRCERROR("PCRE2 ERROR DFA BADRESTART");
            case PCRE2_ERROR_DFA_RECURSE:                      SETRCERROR("PCRE2 ERROR DFA RECURSE");
            case PCRE2_ERROR_DFA_UCOND:                        SETRCERROR("PCRE2 ERROR DFA UCOND");
            case PCRE2_ERROR_DFA_UFUNC:                        SETRCERROR("PCRE2 ERROR DFA UFUNC");
            case PCRE2_ERROR_DFA_UITEM:                        SETRCERROR("PCRE2 ERROR DFA UITEM");
            case PCRE2_ERROR_DFA_WSSIZE:                       SETRCERROR("PCRE2 ERROR DFA WSSIZE");
            case PCRE2_ERROR_INTERNAL:                         SETRCERROR("PCRE2 ERROR INTERNAL");
            case PCRE2_ERROR_JIT_BADOPTION:                    SETRCERROR("PCRE2 ERROR JIT BADOPTION");
            case PCRE2_ERROR_JIT_STACKLIMIT:                   SETRCERROR("PCRE2 ERROR JIT STACKLIMIT");
            case PCRE2_ERROR_MATCHLIMIT:                       SETRCERROR("PCRE2 ERROR MATCHLIMIT");
            case PCRE2_ERROR_NOMEMORY:                         SETRCERROR("PCRE2 ERROR NOMEMORY");
            case PCRE2_ERROR_NOSUBSTRING:                      SETRCERROR("PCRE2 ERROR NOSUBSTRING");
            case PCRE2_ERROR_NOUNIQUESUBSTRING:                SETRCERROR("PCRE2 ERROR NOUNIQUESUBSTRING");
            case PCRE2_ERROR_NULL:                             SETRCERROR("PCRE2 ERROR NULL");
            case PCRE2_ERROR_RECURSELOOP:                      SETRCERROR("PCRE2 ERROR RECURSELOOP");
            case PCRE2_ERROR_DEPTHLIMIT:                       SETRCERROR("PCRE2 ERROR DEPTHLIMIT");
            // obsolote value:
            // case PCRE2_ERROR_RECURSIONLIMIT:                   SETRCERROR("PCRE2 ERROR RECURSIONLIMIT");
            case PCRE2_ERROR_UNAVAILABLE:                      SETRCERROR("PCRE2 ERROR UNAVAILABLE");
            case PCRE2_ERROR_UNSET:                            SETRCERROR("PCRE2 ERROR UNSET");
            case PCRE2_ERROR_BADOFFSETLIMIT:                   SETRCERROR("PCRE2 ERROR BADOFFSETLIMIT");
            case PCRE2_ERROR_BADREPESCAPE:                     SETRCERROR("PCRE2 ERROR BADREPESCAPE");
            case PCRE2_ERROR_REPMISSINGBRACE:                  SETRCERROR("PCRE2 ERROR REPMISSINGBRACE");
            case PCRE2_ERROR_BADSUBSTITUTION:                  SETRCERROR("PCRE2 ERROR BADSUBSTITUTION");
            case PCRE2_ERROR_BADSUBSPATTERN:                   SETRCERROR("PCRE2 ERROR BADSUBSPATTERN");
            case PCRE2_ERROR_TOOMANYREPLACE:                   SETRCERROR("PCRE2 ERROR TOOMANYREPLACE");
            case PCRE2_ERROR_BADSERIALIZEDDATA:                SETRCERROR("PCRE2 ERROR BADSERIALIZEDDATA");
            case PCRE2_ERROR_HEAPLIMIT:                        SETRCERROR("PCRE2 ERROR HEAPLIMIT");
            case PCRE2_ERROR_CONVERT_SYNTAX:                   SETRCERROR("PCRE2 ERROR CONVERT SYNTAX");
            case PCRE2_ERROR_INTERNAL_DUPMATCH:                SETRCERROR("PCRE2 ERROR INTERNAL DUPMATCH");
            case PCRE2_ERROR_DFA_UINVALID_UTF:                 SETRCERROR("PCRE2 ERROR DFA UINVALID UTF");
            case PCRE2_ERROR_INVALIDOFFSET:                    SETRCERROR("PCRE2 ERROR INVALIDOFFSET");
            case PCRE2_ERROR_JIT_UNSUPPORTED:                  SETRCERROR("PCRE2 ERROR JIT UNSUPPORTED");
            case PCRE2_ERROR_REPLACECASE:                      SETRCERROR("PCRE2 ERROR REPLACECASE");
            case PCRE2_ERROR_TOOLARGEREPLACE:                  SETRCERROR("PCRE2 ERROR TOOLARGEREPLACE");
            default:
                if (rc > 0) {
                    sprintf(rcerror, "SUBJECT MATCHED %d TIME%s", rc, ((rc > 1) ? "S" : ""));
                }
        }
#ifdef WITH_OLD_PCRE
    }
#endif
}

int compare_ld (const void * a, const void * b) {
  if (*(long double*)a > *(long double*)b) return 1;
  else if (*(long double*)a < *(long double*)b) return -1;
  else return 0;
}

long double calc_std_deviation(const long double * arr, const int n, const long double avg) {
    long double sum = 0.0;
    for(int i = 0; i < n; i++) {
        sum += powl(arr[i]-avg, 2.0);
    }
    return sqrtl(sum/((long double)n));
}

void show_stat(long double * ld_diffs, int icnt) {

    if (icnt == 0) {
        return;
    }

    double long ld_mean = 0.0, ld_med = 0.0, ld_sums = 0.0;
    double long ld_minval = 0.0, ld_maxval = 0.0;

#ifdef __cplusplus
    qsort(&ld_diffs[0], icnt, sizeof(long double), compare_ld);
#else
    qsort(ld_diffs, icnt, sizeof(long double), compare_ld);
#endif

    ld_minval = ld_diffs[0];
    ld_maxval = ld_diffs[icnt-1];

    for(int i = 0; i < icnt; i++) {
        ld_sums += ld_diffs[i];
    }

    ld_mean = ld_sums / (double)icnt;

    if (icnt%2 == 1) {
        ld_med = ld_diffs[(icnt/2)+1];
    }
    else {
        long double ldtemp[2];
        ldtemp[0] = ld_diffs[(icnt/2)];
        ldtemp[1] = ld_diffs[(icnt/2)+1];
        ld_med = ldtemp[0] + ((ldtemp[1]-ldtemp[0])/2.0);
    }

    printf("Num of values: %d\n", icnt);
    printf("         Mean: %013.9Lf\n", ld_mean);
    printf("       Median: %013.9Lf\n", ld_med);
    printf("          Min: %013.9Lf\n", ld_minval);
    printf("          Max: %013.9Lf\n", ld_maxval);
    printf("        Range: %013.9Lf\n", ld_maxval - ld_minval);
#ifdef __cplusplus
    printf("Std deviation: %013.9Lf\n", calc_std_deviation(&ld_diffs[0], icnt, ld_mean));
#else
    printf("Std deviation: %013.9Lf\n", calc_std_deviation(ld_diffs, icnt, ld_mean));
#endif
}